print(1 + 1) # addition (= 2)
print(2 * 5) # multiplication (= 10)
print(2 ** 2) # exponent (2 to the power of 2 = 4)
print (5 / 2) # division (= 2.5)
print(5 // 2) # floor division (= 2)
print(5 % 2) # modulo or reminder of division (= 1)
