@startuml adapter_pattern

interface Pizza
Pizza : description()
Pizza : cost()

Pizza <|.. ThinCrustPizza
Pizza <|.. ThickCrustPizza

abstract Topping
Pizza <|.. Topping
Pizza o-- Topping
Topping : Pizza decorated

Topping <|-- Cheese
Topping <|-- Olive
Topping <|-- Peppers

@enduml