@startuml observer_pattern

interface WeatherObserver
WeatherObserver : update(temp, wind, pressure)

GUI ..> WeatherObserver
Logger ..> WeatherObserver
AlertSystem ..> WeatherObserver

class WeatherStation
WeatherStation : temperature
WeatherStation : windSpeed
WeatherStation : presure
WeatherStation : WeatherObserver observers
 
WeatherStation "1" o--- "*" WeatherObserver
WeatherStation : notifyObservers()

@enduml