# Simple workflow for deploying static content to GitHub Pages
name: Deploy static projects to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir public
      - name: Copy all static projects to public dir
        run: echo '<h1>Github Actions & Github Pages are awesome 😎</h1>' > ./public/index.html
      - run: cp -r ./02-Udemy/-01-HTML-CSS-Jonas/Projects/* ./public
      - run: cp -r ./02-Udemy/-02-Js-Andrew/Projects/* ./public
      - run: ls ./public
      # add a step to generate an index.html page for all hosted projects
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact to github pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
